#!/usr/bin/env python3
"""Generate the site's official zh-TW character display-name map.

Canonical Korean keys and resource ids come only from scraper/nikke_scraped.json.
For each id, this script reads the live BlablaLink CDN role record at
/roledata/{resource_id}-v2-zh-tw.json and keeps only name_localkey. It does not
store a second copy of the raw role data.

The script uses only the Python standard library and the repository's canonical
CDN path helper:

    python3 site/scripts/update-character-names-zh-tw.py
    python3 site/scripts/update-character-names-zh-tw.py --check
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
from pathlib import Path
import sys
import time
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "scraper" / "nikke_scraped.json"
OUTPUT = ROOT / "site" / "src" / "i18n" / "character-names-zh-tw.ts"
LOCALE = "zh-tw"
WORKERS = 8

sys.path.insert(0, str(ROOT))
from scraper.cdn_path import url as cdn_url  # noqa: E402


def fetch_name(resource_id: int) -> str:
    path = f"/roledata/{resource_id}-v2-{LOCALE}.json"
    request = Request(cdn_url(path), headers={"User-Agent": "nikke-calc-name-map/1"})
    last_error: Exception | None = None
    for attempt in range(3):
        try:
            with urlopen(request, timeout=20) as response:
                role = json.load(response)
            if role.get("resource_id") != resource_id:
                raise ValueError(
                    f"resource id mismatch: requested {resource_id}, "
                    f"received {role.get('resource_id')!r}"
                )
            name = role.get("name_localkey")
            if not isinstance(name, str) or not name.strip():
                raise ValueError(f"resource {resource_id} has no name_localkey")
            return name.strip()
        except (HTTPError, URLError, TimeoutError, ValueError, json.JSONDecodeError) as error:
            last_error = error
            if attempt < 2:
                time.sleep(0.5 * (2**attempt))
    raise RuntimeError(f"failed to fetch {path}: {last_error}")


def load_characters() -> list[tuple[str, int]]:
    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    characters: list[tuple[str, int]] = []
    seen_ids: set[int] = set()
    for canonical_name, details in raw.items():
        resource_id = details.get("id")
        if not isinstance(resource_id, int):
            raise ValueError(f"{canonical_name}: missing integer id")
        if resource_id in seen_ids:
            raise ValueError(f"duplicate resource id: {resource_id}")
        seen_ids.add(resource_id)
        characters.append((canonical_name, resource_id))
    return characters


def render(mapping: dict[str, str]) -> str:
    rows = [
        "// Generated by site/scripts/update-character-names-zh-tw.py.",
        "// Source: live BlablaLink CDN /roledata/{resource_id}-v2-zh-tw.json",
        "// Canonical keys/resource ids: scraper/nikke_scraped.json",
        "// Derived display names only; Korean keys remain the application's identifiers.",
        "",
        "export const characterNamesZhTW: Readonly<Record<string, string>> = {",
    ]
    for canonical_name, display_name in mapping.items():
        rows.append(
            f"  {json.dumps(canonical_name, ensure_ascii=False)}: "
            f"{json.dumps(display_name, ensure_ascii=False)},"
        )
    rows.extend(["};", ""])
    return "\n".join(rows)


def build_mapping(characters: list[tuple[str, int]]) -> dict[str, str]:
    fetched: dict[str, str] = {}
    failures: list[str] = []
    with ThreadPoolExecutor(max_workers=WORKERS) as executor:
        pending = {
            executor.submit(fetch_name, resource_id): (canonical_name, resource_id)
            for canonical_name, resource_id in characters
        }
        for future in as_completed(pending):
            canonical_name, resource_id = pending[future]
            try:
                fetched[canonical_name] = future.result()
            except Exception as error:  # report every missing record in one run
                failures.append(f"{canonical_name} ({resource_id}): {error}")
    if failures:
        raise RuntimeError("CDN name fetch failed:\n  " + "\n  ".join(sorted(failures)))
    return {name: fetched[name] for name, _resource_id in characters}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed mapping differs from the current CDN",
    )
    args = parser.parse_args()

    characters = load_characters()
    content = render(build_mapping(characters))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is current ({len(characters)} names)")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(characters)} names)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
