// Generated by site/scripts/update-equipment-names-zh-tw.py.
// Source: live BlablaLink CDN /equip/zh-tw/{cube,favorite}_{id}.json
// Canonical keys/IDs: data/base_stat_tables/cube.json and scraper/nikke_scraped.json
// Derived display names only; Korean keys remain the application's identifiers.

export const cubeNamesZhTW: Readonly<Record<string, string>> = {
  "렐릭 어설트 큐브": "遺跡突擊魔方",
  "택티컬 어설트 큐브": "戰術突擊魔方",
  "렐릭 베어 큐브": "遺跡巨熊魔方",
  "택티컬 베어 큐브": "戰術巨熊魔方",
  "렐릭 부스트 큐브": "遺跡促進魔方",
  "택티컬 부스트 큐브": "戰術促進魔方",
  "렐릭 퀀텀 큐브": "遺跡量子魔方",
  "렐릭 비고르 큐브": "體力神器魔方",
  "렐릭 인듀어 큐브": "遺跡強韌魔方",
  "렐릭 힐링 큐브": "遺跡治療魔方",
  "렐릭 템퍼링 큐브": "遺跡回火魔方",
  "렐릭 어시스터 큐브": "遺跡輔助魔方",
  "렐릭 디스트로이 큐브": "遺跡毀滅魔方",
  "렐릭 피어싱 큐브": "遺跡穿透魔方",
  "렐릭 크래시 큐브": "遺跡粉碎魔方",
  "렐릭 커버 큐브": "遺跡掩體魔方",
  "렐릭 디바이드 큐브": "遺跡分裂魔方",
};

export const favoriteItemNamesZhTW: Readonly<Record<string, string>> = {
  "형사 수첩": "刑警手冊",
  "롤링 페이퍼": "手寫信",
  "장난감 기차 세트": "玩具火車套組",
  "금속 목걸이": "金屬項鍊",
  "히어로 트릴로지 BD": "《英雄三部曲》藍光光碟",
  "빌런 피규어": "反派模型",
  "첫 휴대폰과 연락처 수첩": "第一支手機和聯絡人紀錄簿",
  "기념 열쇠고리": "紀念鑰匙圈",
  "커플 머그잔": "情侶馬克杯",
  "애착 베개": "心愛的枕頭",
  "음악 노트": "樂譜筆記",
  "중앙 정부 특별 훈장": "中央政府特別勳章",
  "파이어 스타터": "打火器",
  "게임 키드 에볼루션": "Gamekid EVO",
  "인장 반지": "印章戒指",
  "모란꽃 모양 비녀": "牡丹花造型髮簪",
  "낡은 나침반": "老舊的羅盤",
  "네잎클로버 책갈피": "四葉草書籤",
  "함께 만든 화분": "共同製作的花盆",
  "연습용 신발": "啦啦隊鞋",
  "소중한 가면들": "珍貴的面具們",
};
